### ISSUE TITLE
Домашка №1, HTML

### ISSUE THREAD

**Issue by tiny-kottan** [aerobium/kottans-JS-2016#3]
Разметить эту страницу: https://habrahabr.ru/post/244929/
от вас ожидаеться `.html` файл с семантичной разметкой, без css/js
крупные части контента копипастить не стоит (саму статью, там `h*`/`p`/`code` -- все просто), а вот остальное -- нужно
как должно выглядить

`````` html
<!doctype html>
<html lang=ru>
<meta charset=utf-8>
<title>Habrahabr.ru</title>
<header>
  <ul>
    <li><a href=...>TM Feed</a>
    <li><a>Хабрахабр</a>
  </ul>```
``````

**Comment by aerobium** [comment]
https://github.com/aerobium/kottans-JS-2016/tree/master/week01/lec1

**Comment by mkozhukharenko** [comment]
event github editor shodw that is't wrong

``` html
<!------------------------------------------------------->
```

correct:

``` html
<!-- - - - - - - - - - - - - - - -->
```

**Comment by mkozhukharenko** [comment]
I'd rather use heading instead of a span

``` html
<header>
    <aside>
        <span>Разделы</span>
```

**Comment by mkozhukharenko** [comment]
it's two separate sections:

``` html
 <!-- section 1 -->
<span>Разделы</span>
        <input type="text" placeholder="Поиск">
        <ul>
            <li><a href="">Публикации</a></li>
            <li><a href="">Хабы</a></li>
            <li><a href="">Компании</a></li>
            <li><a href="">Пользователи</a></li>
        </ul>
        <hr>
 <!-- section 2 -->
        <span>Спецпроекты</span>
        <ul>
            <li><a href="">Соберите свой стартап</a></li>
            <li><a href="">Linux в Azure</a></li>
            <li><a href="">Создай игру</a></li>
        </ul>
```

**Comment by mkozhukharenko** [comment]
"Основной центральный блок" should be either a comment or wrapped into some element, e.g. h1

**Comment by mkozhukharenko** [comment]
it's half done.

``` html
<section>
        <figure>
            Аватарка
        </figure>
        <a href="">@rayproud</a>
        <meter value=""></meter>
        <meter value=""></meter>
        <p><span>Пользователь</span> <span>карма</span><span>рейтинг</span></p>
```

**Comment by mkozhukharenko** [comment]
I'd add a full time for this 

``` html
 <time datetime="2014-12-03">3 декабря 2014 в 16:57</time>
```

e.g. 

``` js
datetime="2006-09-24T05:00-07:00"
```

you can use this pattern: `ГГГГ-ММ-ДДTчч:мм:сс±чч:мм`

**Comment by mkozhukharenko** [comment]
this

``` html
<aside>Правый рекламный блок</aside>
<aside>
    <h2>Хабы</h2>
```

should be 

```
<aside>/aside>
<aside>
    <h2>Правый рекламный блок</h2>
```

**Comment by mkozhukharenko** [comment]
I would wrap this into separate sections

``` html
 <ul>
            <li><a href="">Войти</a>
            <li><a href="">Регистрация</a>
        </ul>
        <p>Разделы</p>
        <ul>
            <li><a href="">Войти</a>
            <li><a href="">Регистрация</a>
        </ul>
        <p>Инфо</p>
        <ul>
            <li><a href="">О сайте</a>
            <li><a href="">Правила</a>
        </ul>
        <p>Услуги</p>
        <ul>
            <li><a href="">Реклама</a>
            <li><a href="">Спецпроекты</a>
        </ul>
        <p>Разное</p>
        <ul>
            <li><a href="">Приложения</a>
            <li><a href="">Тест-драйв</a>
        </ul>
```

**Comment by aerobium** [comment]
Thank you for you feedback!

I fixed my work with you comment.

**Comment by mkozhukharenko** [comment]
please, add link to this task in a commit message 
instead of "fix and refactor" should be "#2 fix and refactor"

**Comment by mkozhukharenko** [comment]
You missed this https://github.com/aerobium/kottans-JS-2016/issues/3#issuecomment-220836754

**Comment by mkozhukharenko** [comment]
reopen an issue please

**Comment by mkozhukharenko** [comment]
``` html
<span>Спецпроекты</span>
```

should be a heading

**Comment by mkozhukharenko** [comment]
Look at comments again and fix not exactly them but a related issues as well. 
😕 
e,g, this comment https://github.com/aerobium/kottans-JS-2016/issues/3#issuecomment-220836632 isn't mean fixing the exactly this issue. Try to find a similar ones and fix them as well, please.

**Comment by aerobium** [comment]
[#3](https://github.com/aerobium/kottans-JS-2016/issues/3#issuecomment-220836754) I forgot about another the same place.

> e,g, this comment #3 (comment) isn't mean fixing the exactly this issue. Try to find a similar ones and fix them as well, please.

I didn't find :-(

**Comment by mkozhukharenko** [comment]
``` html
            <figure>Аватарка</figure>
            <span>Никнейм</span>
```

expand this markup using a [knowledge](http://html5doctor.com/the-figure-figcaption-elements/) from this article

**Comment by mkozhukharenko** [comment]
> I didn't find :-(

me too 😄

**Comment by mkozhukharenko** [comment]
``` html
<header>
    <aside>
        <section>
            <h3>Разделы</h3>
            <input type="text" placeholder="Поиск">
            <ul>
                <li><a href="">Публикации</a></li>
                <li><a href="">Хабы</a></li>
                <li><a href="">Компании</a></li>
                <li><a href="">Пользователи</a></li>
            </ul>
            <hr>
        </section>
        <section>
            <h3>Спецпроекты</h3>
            <ul>
                <li><a href="">Соберите свой стартап</a></li>
                <li><a href="">Linux в Azure</a></li>
                <li><a href="">Создай игру</a></li>
            </ul>
        </section>
    </aside>
</header>
```

somewhere here should be a `nav` element
read [this](http://html5doctor.com/avoiding-common-html5-mistakes/#nav-external) to find out how to use this element

**Comment by mkozhukharenko** [comment]
do you really need [this section?](https://github.com/aerobium/kottans-JS-2016/blob/master/week01/lec1/index.html#L105) I think it serve only for styling purposes.

**Comment by aerobium** [comment]
[#3](https://github.com/aerobium/kottans-JS-2016/issues/3#issuecomment-220977262)
What do ve have: we have the avatar. And it's all.
This is not a figure with multiple images, not figure with code. There is not even a signature (maybe nickname). This figure is only a picture. Can it be not a figure? Maybe it is simple <img>?
But now I have two variants. If some of them is good - I will fix another.

**Comment by mkozhukharenko** [comment]
@aerobium, good that you casted doubt on that proposal. I can't agree more with your arguments. Do we have other options? 

> But now I have two variants.
> can you describe them?

**Comment by aerobium** [comment]
> can you describe them?

```
<figure>
   <a href=""><img src="" alt=""></a>
</figure>
```

and another

```
<figure>
 <a href=""><img src="" alt=""></a>
 <figcaption><a href="">Nickname</a></figcaption>
</figure>
```

another variant - simple `<img>`

**Comment by mkozhukharenko** [comment]
``` html
  <figure>
       <a href=""><img src="" alt=""></a>
       <figcaption><a href="">Nickname</a></figcaption>
   </figure>
```

this it that I meant. 

But simple img would be fine as well. 
Have you read this [chapter](http://html5doctor.com/avoiding-common-html5-mistakes/#figure)?

**Comment by aerobium** [comment]
[#3](https://github.com/aerobium/kottans-JS-2016/issues/3#issuecomment-220977842)
What I think about the `<nav>` after reading the article. In our case, `<nav>` suitable only for the top  menu, as it is constant and links to site contents. While the bottom menu may sometimes change their contents. Moreover, the bottom menu links to specific projects (like advertisement) - it's not quite site navigation.
I fixed it.

**Comment by aerobium** [comment]
[#3](https://github.com/aerobium/kottans-JS-2016/issues/3#issuecomment-220978208)
You are right

**Comment by aerobium** [comment]
[#3](https://github.com/aerobium/kottans-JS-2016/issues/3#issuecomment-221178576)

> Have you read this chapter?

Yes, I have. From the beginning, I wanted to use `<img>` (becuse it is that situation, when there is no need to complicate). But on lectures our speaker suggested to use `<figure>`...
